class Assignment:
  def __init__(
    self,
    assignedassignment_id: str = None,
    state: str = None,
    is_past: str = None,
    is_late: str = None,
    end_date: str = None,
    is_process: str = None,
    startable: str = None,
    is_approved: str = None,
    is_archived: str = None,
    can_reflect: str = None,
    can_withdraw: str = None,
    soft_end_date: str = None,
    connectable_key: str = None,
    end_date_formatted: str = None,
    feedback_can_answer: str = None,
    approved_at_formatted: str = None,
    delivered_at_formatted: str = None,
    optional_reflection: str = None,
    optional_uncompleted_reflection: str = None,
    used_feedback: str = None,
    question_left_feedback: str = None,
    reviewer_name: str = None,
    reviewer_id: str = None,
    reviewer_avatar: str = None,
    reviewer_username: str = None,
    reviewer_permalink: str = None,
    approver_id: str = None,
    approver_name: str = None,
    approver_avatar: str = None,
    approver_username: str = None,
    approver_permalink: str = None,
    assignment_id: str = None,
    icon: str = None,
    title: str = None,
    is_deleted: str = None,
    badges_count: int = None,
    feedback_count: int = None,
    actual_deliverables_count: int = None,
    badges_id: str = None,
    badges_name: str = None,
    badges_type: str = None,
    badges_level: int = None,
    badges_is_optional: str = None,
    badges_description: str = None,
    badges_blocks_id: str = None,
    badges_blocks_type: str = None,
    badges_blocks_content: str = None,
    weights_color: str = None,
    weights_level: int = None,
    weights_title: str = None,
    weights_image: str = None,
    criteria_id: str = None,
    criteria_name: str = None,
    criteria_order: str = None,
    criteria_formatted_content: str = None,
    criteria_level: int = None,
    criteria_weight: str = None,
    tags_id: str = None,
    tags_name: str = None,
    cover_id: str = None,
    cover_url: str = None,
    blocks_id: str = None,
    blocks_type: str = None,
    blocks_title: str = None,
    blocks_content: str = None,
    blocks_is_presentable: str = None,
    resources_id: str = None,
    resources_url: str = None,
    resources_title: str = None,
    deliverable_id: str = None,
    deliverable_type: str = None,
    deliverable_title: str = None,
    deliverable_minimum: int = None,
    deliverable_multiple: str = None,
    deliverable_is_optional: bool = None,
    deliverable_description: str = None,
    deliverable_requirements: str = None,
    deliverable_post_min_words: str = None,
    deliverable_post_max_words: str = None,
    statusmessage_text: str = None,
    statusmessage_color: str = None,



  ) -> None:
    self.assignedassignment_id = assignedassignment_id
    self.state = state
    self.is_past = is_past
    self.is_late = is_late
    self.end_date = end_date
    self.is_process = is_process
    self.startable = startable
    self.is_approved = is_approved
    self.is_archived = is_archived
    self.can_reflect = can_reflect
    self.can_withdraw = can_withdraw
    self.soft_end_date = soft_end_date
    self.connectable_key = connectable_key
    self.end_date_formatted = end_date_formatted
    self.feedback_can_answer = feedback_can_answer
    self.approved_at_formatted = approved_at_formatted
    self.delivered_at_formatted = delivered_at_formatted
    self.optional_reflection = optional_reflection
    self.optional_uncompleted_reflection = optional_uncompleted_reflection
    self.used_feedback = used_feedback
    self.question_left_feedback = question_left_feedback
    self.reviewer_name = reviewer_name
    self.reviewer_id = reviewer_id
    self.reviewer_avatar = reviewer_avatar
    self.reviewer_username = reviewer_username
    self.reviewer_permalink = reviewer_permalink
    self.approver_id = approver_id
    self.approver_name = approver_name
    self.approver_avatar = approver_avatar
    self.approver_username = approver_username
    self.approver_permalink = approver_permalink
    self.assignment_id = assignment_id
    self.icon = icon
    self.title = title
    self.is_deleted = is_deleted
    self.badges_count = badges_count
    self.feedback_count = feedback_count
    self.actual_deliverables_count = actual_deliverables_count
    self.badges_id = badges_id
    self.badges_name = badges_name
    self.badges_type = badges_type
    self.badges_level = badges_level
    self.badges_is_optional = badges_is_optional
    self.badges_description = badges_description
    self.badges_blocks_id = badges_blocks_id
    self.badges_blocks_type = badges_blocks_type
    self.badges_blocks_content = badges_blocks_content
    self.weights_color = weights_color
    self.weights_level = weights_level
    self.weights_title = weights_title
    self.weights_image = weights_image
    self.criteria_id = criteria_id
    self.criteria_name = criteria_name
    self.criteria_order = criteria_order
    self.criteria_formatted_content = criteria_formatted_content
    self.criteria_level = criteria_level
    self.criteria_weight = criteria_weight
    self.tags_id = tags_id
    self.tags_name = tags_name
    self.cover_id = cover_id
    self.cover_url = cover_url
    self.blocks_id = blocks_id
    self.blocks_type = blocks_type
    self.blocks_title = blocks_title
    self.blocks_content = blocks_content
    self.blocks_is_presentable = blocks_is_presentable
    self.resources_id = resources_id
    self.resources_url = resources_url
    self.resources_title = resources_title
    self.deliverable_id = deliverable_id
    self.deliverable_type = deliverable_type
    self.deliverable_title = deliverable_title
    self.deliverable_minimum = deliverable_minimum
    self.deliverable_type = deliverable_type
    self.deliverable_is_optional = deliverable_is_optional
    self.deliverable_description = deliverable_description
    self.deliverable_requirements = deliverable_requirements
    self.deliverable_post_min_words = deliverable_post_min_words
    self.deliverable_post_max_words = deliverable_post_max_words
    self.statusmessage_text = statusmessage_text
    self.statusmessage_color = statusmessage_color